"""Pure lifecycle authority for broker jobs and generations."""

from .errors import (
    BrokerError,
    ConcurrentMutation,
    IdempotencyConflict,
    InvalidTransition,
    JobNotFound,
    MigrationProblem,
    MigrationVersionError,
    OperationMismatch,
    OwnerMismatch,
    ReceiptField,
    ReceiptBindingMismatch,
    StaleGeneration,
    TransitionEntity,
)
from .models import (
    AuditRecord,
    BrokerOwner,
    CommandKind,
    GenerationRecord,
    GenerationSnapshot,
    GenerationState,
    JobRecord,
    JobSnapshot,
    JobState,
    OperationRecord,
    OperationResult,
    OperationSource,
    OperationStatus,
    OperationTicket,
    RecoveryCandidate,
    RecoverySnapshot,
    ReleaseTarget,
    SignedCheckpointReceipt,
    TerminalOutcome,
    VerifiedCheckpointReceipt,
)
from .ledger import BrokerLedger
from .memory import InMemoryBrokerRepository
from .postgres import PostgresBrokerRepository
from .repository import BrokerRepository

__all__ = [
    "AuditRecord",
    "BrokerError",
    "BrokerLedger",
    "BrokerOwner",
    "BrokerRepository",
    "CommandKind",
    "ConcurrentMutation",
    "GenerationRecord",
    "GenerationSnapshot",
    "GenerationState",
    "IdempotencyConflict",
    "InvalidTransition",
    "InMemoryBrokerRepository",
    "JobNotFound",
    "JobRecord",
    "JobSnapshot",
    "JobState",
    "MigrationProblem",
    "MigrationVersionError",
    "OperationMismatch",
    "OperationRecord",
    "OperationResult",
    "OperationSource",
    "OperationStatus",
    "OperationTicket",
    "OwnerMismatch",
    "PostgresBrokerRepository",
    "ReceiptField",
    "ReceiptBindingMismatch",
    "RecoveryCandidate",
    "RecoverySnapshot",
    "ReleaseTarget",
    "SignedCheckpointReceipt",
    "StaleGeneration",
    "TerminalOutcome",
    "TransitionEntity",
    "VerifiedCheckpointReceipt",
]
