"""Shared test helpers and lightweight fakes.

These helpers are intentionally network-free and database-free. They are used
by OpenLoop's own tests and can also support downstream integration tests.
"""

import shutil
import tempfile
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

from openloop.config import Settings
from openloop.memory.embeddings import Embedder
from openloop.models.gateway import ModelResponse, ToolCall
from openloop.tasks.outcomes import EvidenceBundle
from openloop.usage import WorkerSpendLedger
from openloop.workflows import InMemoryWorkflowStore, WorkflowEngine


def in_memory_workflow_engine() -> WorkflowEngine:
    """Return a fresh, explicitly non-durable workflow engine for one test."""
    return WorkflowEngine(InMemoryWorkflowStore())


@asynccontextmanager
async def memory_context(
    settings: Settings | None = None,
    agents=None,
    *,
    overrides: dict[str, Any] | None = None,
):
    """Compose the real application graph with explicitly process-local stores."""
    from openloop.wiring import compose

    configured = (settings or Settings()).model_copy(
        update={"storage_mode": "memory"}
    )
    async with compose(configured, agents, overrides=overrides) as ctx:
        yield ctx


def tool_call_response(model: str, calls: list[tuple[str, str, dict]]) -> ModelResponse:
    """Build a ModelResponse that asks for tool calls.

    `calls` is a list of (call_id, function_name, arguments).
    """
    import json

    tool_calls = [ToolCall(id=cid, name=name, arguments=args)
                  for cid, name, args in calls]
    raw_message = {
        "role": "assistant",
        "content": None,
        "tool_calls": [
            {"id": cid, "type": "function",
             "function": {"name": name, "arguments": json.dumps(args)}}
            for cid, name, args in calls
        ],
    }
    return ModelResponse(text="", model=model, tool_calls=tool_calls,
                         raw_message=raw_message)


class ScriptedGateway:
    """Returns a pre-scripted sequence of ModelResponses, recording each call."""

    def __init__(self, responses: list[ModelResponse]) -> None:
        self._responses = list(responses)
        self.calls: list[dict] = []

    async def complete(self, model, messages, **kwargs) -> ModelResponse:
        self.calls.append(
            {"model": model, "messages": list(messages), "tools": kwargs.get("tools")}
        )
        return self._responses.pop(0)


class FakeGateway:
    """Records the messages it was called with and returns a canned reply."""

    def __init__(self, reply: str = "ok") -> None:
        self.reply = reply
        self.last_messages: list[dict[str, str]] | None = None
        self.last_model: str | None = None

    async def complete(self, model, messages, **kwargs) -> ModelResponse:
        self.last_model = model
        self.last_messages = messages
        return ModelResponse(text=self.reply, model=model)


class FakeGitHub:
    """In-memory GitHub client that records calls without using the network."""

    def __init__(self) -> None:
        self.created: list[dict] = []
        self.pulls: list[dict] = []

    async def create_issue(self, repo, title, body):
        issue = {"number": len(self.created) + 1, "repo": repo, "title": title}
        self.created.append(issue)
        return issue

    async def get_issue(self, repo, number):
        return {"number": number, "repo": repo, "state": "open"}

    async def get_pull(self, repo, number):
        return {"number": number, "repo": repo, "state": "open"}

    async def create_pull(self, repo, head, base, title, body, draft=True):
        number = len(self.pulls) + 1
        pull = {
            "number": number,
            "repo": repo,
            "head": head,
            "base": base,
            "title": title,
            "body": body,
            "draft": draft,
            "html_url": f"https://github.com/{repo}/pull/{number}",
        }
        self.pulls.append(pull)
        return pull

    async def find_pull(self, repo, head):
        for pull in self.pulls:
            if pull["repo"] == repo and pull["head"] == head:
                return pull
        return None


class FakeCodingWorker:
    """A credential-free CodingWorker fake: records runs, returns a canned edit.

    Matches the Phase 2 contract — it receives a *prepared* workspace and only
    reports its own ``edit`` step; git and credentials are the orchestrator's.
    """

    def __init__(
        self,
        title: str = "Automated change",
        body: str = "Generated by the coding worker.",
        *,
        cost_usd: float = 0.0,
        prompt_tokens: int = 0,
        completion_tokens: int = 0,
    ) -> None:
        self.title = title
        self.body = body
        self.cost_usd = cost_usd
        self.prompt_tokens = prompt_tokens
        self.completion_tokens = completion_tokens
        self.runs: list = []

    async def run(self, workspace, state, on_step=None):
        from openloop.tools.coding_worker import WorkerEdit

        state.completed_steps.append("edit")
        if on_step is not None:
            await on_step(state)
        self.runs.append((workspace, state))
        return WorkerEdit(
            title=self.title,
            body=self.body,
            cost_usd=self.cost_usd,
            prompt_tokens=self.prompt_tokens,
            completion_tokens=self.completion_tokens,
        )


class FakeWorkerOrchestrator:
    """An AttemptRunner that records attempts and returns a canned outcome.

    Walks the named steps (calling ``on_step`` after each, so checkpointing can
    be exercised) without touching git, a model, or a credential — network-free.
    Stands in for :class:`~openloop.tools.coding_worker.GitWorkspaceOrchestrator`
    wherever a durable path needs an attempt run.
    """

    def __init__(
        self,
        title: str = "Automated change",
        body: str = "Generated by the coding worker.",
        *,
        cost_usd: float = 0.0,
        prompt_tokens: int = 0,
        completion_tokens: int = 0,
        seed_files: dict[str, str] | None = None,
        ledger: WorkerSpendLedger | None = None,
        investigation_summary: str = "fake investigation summary",
        investigation_findings: str = "- (fake) no findings",
    ) -> None:
        self.title = title
        self.body = body
        self.cost_usd = cost_usd
        self.prompt_tokens = prompt_tokens
        self.completion_tokens = completion_tokens
        self.runs: list = []
        # Files written into every workspace returned by provision_readonly,
        # so a fake investigation has something to read without a real clone.
        self.seed_files = seed_files
        self.readonly_provisions: list[tuple[str, str | None]] = []
        # Optional spend ledger: when set, run_investigation brackets it the
        # same way GitWorkspaceOrchestrator.run_investigation does — network-
        # free, but ledger-accurate for tests that exercise spend tracking
        # against a fake orchestrator.
        self._ledger = ledger
        self.investigation_summary = investigation_summary
        self.investigation_findings = investigation_findings
        self.investigations: list = []

    async def run_attempt(self, state, on_step=None):
        from openloop.tools.coding_worker import STEPS, WorkerOutcome

        for step in STEPS:
            state.completed_steps.append(step)
            if on_step is not None:
                await on_step(state)
        state.title, state.body = self.title, self.body
        self.runs.append(state)
        return WorkerOutcome(
            branch=state.branch,
            title=self.title,
            body=self.body,
            cost_usd=self.cost_usd,
            prompt_tokens=self.prompt_tokens,
            completion_tokens=self.completion_tokens,
        )

    async def provision_readonly(self, repo: str, ref: str | None = None) -> Path:
        """A network-free stand-in for GitWorkspaceOrchestrator.provision_readonly.

        Returns a fresh tmp dir (optionally seeded with files) instead of
        cloning — no git, no credential, no network.
        """
        workspace = Path(tempfile.mkdtemp(prefix="openloop-investigate-fake-"))
        self.readonly_provisions.append((repo, ref))
        for name, content in (self.seed_files or {}).items():
            (workspace / name).write_text(content)
        return workspace

    async def run_investigation(self, task, investigator=None):
        """A network-free stand-in for GitWorkspaceOrchestrator.run_investigation.

        Returns a canned ``(EvidenceBundle, ModelResponse)`` — built from this
        fake's own ``cost_usd``/``prompt_tokens``/``completion_tokens`` and
        ``investigation_summary``/``investigation_findings`` — instead of
        calling ``investigator`` (which is accepted only for signature parity
        with the real orchestrator; matches how ``run_attempt`` above never
        touches a real worker's behavior either). Still provisions and
        discards a real (fake) read-only workspace via ``provision_readonly``,
        so call-recording (``readonly_provisions``) stays accurate. When a
        ledger is set, brackets it exactly like the real
        ``run_investigation`` — ``check_monthly`` before, ``settle`` after —
        sourcing attribution from ``task``, so a capped agent still fails
        closed against a fake orchestrator.
        """
        inputs = task.profile_state["investigate"]
        repo = inputs["repo"]
        ref = inputs.get("ref")

        if self._ledger is not None:
            await self._ledger.check_monthly(
                task.agent,
                agent_id=task.agent_id,
                job_id=task.task_id,
                approval_id=task.approval_id,
                approver=task.requester_id,
                session_id=task.session_id,
            )

        workspace = await self.provision_readonly(repo, ref)
        try:
            self.investigations.append(task)
            resp = ModelResponse(
                text="",
                model="fake",
                cost_usd=self.cost_usd,
                prompt_tokens=self.prompt_tokens,
                completion_tokens=self.completion_tokens,
            )
            bundle = EvidenceBundle(
                summary=self.investigation_summary,
                findings=self.investigation_findings,
            )
            if self._ledger is not None:
                await self._ledger.settle(
                    agent=task.agent,
                    agent_id=task.agent_id,
                    job_id=task.task_id,
                    approval_id=task.approval_id,
                    approver=task.requester_id,
                    session_id=task.session_id,
                    cost_usd=resp.cost_usd,
                    prompt_tokens=resp.prompt_tokens,
                    completion_tokens=resp.completion_tokens,
                )
            return bundle, resp
        finally:
            shutil.rmtree(workspace, ignore_errors=True)


class FakeSurfaceDelivery:
    """In-memory SurfaceDelivery — records delivery calls without a live surface.

    Mints monotonic message ids so the runner's id-guarded idempotency can be
    exercised, and keeps every call for assertions (status, approvals, final).
    Models the keyed-idempotency contract: a tagged post (``key``) is remembered,
    and a ``recover=True`` post with a known key returns the existing id without
    recording a duplicate — exactly the provider-dedup the runner relies on to
    close the post-succeeded-but-id-lost window.
    """

    def __init__(self) -> None:
        self.statuses: list[dict] = []
        self.approvals: list[dict] = []
        self.finals: list[dict] = []
        self.errors: list[dict] = []
        self._seq = 0
        self._by_key: dict[str, str] = {}

    def _next_id(self, prefix: str) -> str:
        self._seq += 1
        return f"{prefix}-{self._seq}"

    def _post(self, bucket: list[dict], prefix: str, record: dict, key, recover) -> str:
        # Recovery of a previously tagged message → return its id, no duplicate.
        if key and recover and key in self._by_key:
            return self._by_key[key]
        mid = self._next_id(prefix)
        if key:
            self._by_key[key] = mid
        bucket.append({"id": mid, **record})
        return mid

    async def set_progress_status(self, target, text) -> None:
        self.statuses.append({"target": target, "text": text})

    async def update_approval(self, target, message_id, text, requests) -> None:
        self.approvals.append(
            {"id": message_id, "target": target, "text": text, "requests": requests}
        )

    async def post_approval(
        self, target, text, requests, *, key=None, recover=False
    ) -> str:
        return self._post(
            self.approvals,
            "approval",
            {"target": target, "text": text, "requests": requests},
            key,
            recover,
        )

    async def post_final(
        self, target, result, *, key=None, recover=False
    ) -> str:
        # `result` is a surface-neutral Deliverable (or plain-string prose);
        # recorded verbatim under "text" so assertions read naturally.
        return self._post(
            self.finals,
            "final",
            {"target": target, "text": result},
            key,
            recover,
        )

    async def post_error(self, target, text, *, key=None, recover=False) -> str:
        return self._post(
            self.errors, "error", {"target": target, "text": text}, key, recover
        )


class FakeEmbedder(Embedder):
    """Deterministic 26-dim bag-of-letters embedding without network calls."""

    async def embed(self, texts: list[str]) -> list[list[float]]:
        return [self._vec(t) for t in texts]

    @staticmethod
    def _vec(text: str) -> list[float]:
        vec = [0.0] * 26
        for ch in text.lower():
            idx = ord(ch) - 97
            if 0 <= idx < 26:
                vec[idx] += 1.0
        return vec
